[package]
name = "lsp"
version = "0.1.0"
edition = "2021"

[dependencies]
tower-lsp = "*"
tokio = { version = "*", features = ["full"] }
serde = { version = "*", features = ["derive"] }
syn = { version = "*", features = ["full", "visit"] }
serde_json = "*"
tracing = "*"
tracing-subscriber = "*"
